"""Fixed foreign key for category

Revision ID: c0e4b50f897f
Revises: 58b986ce131c
Create Date: 2022-05-13 10:54:23.745111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e4b50f897f'
down_revision = '58b986ce131c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
